export * from './home';
export * from './catalog';
export * from './login';
export * from './verify';
export * from './profile';
export * from './checkout';
export * from './success';
export * from './failure';
export * from './pending';